### ISSUE TITLE
Impossible to translate title in store view configuration

### ISSUE THREAD

**Issue by jcourtei** [PowerSync/TNW_Stripe#33]
Hello,
There is an issue in system.xml so it's impossible to translate the title in other languages.
Instead of :
`<group`` id="stripe_required" translate="label" showInDefault="1" showInWebsite="1" sortOrder="5">`
It should be :
`<group id="stripe_required" translate="label" showInDefault="1" showInWebsite="1" showInStore="1" sortOrder="5">`
showInStore parameter is missing.

**Comment by technweb** [comment]
Pull request created: #36

**Comment by technweb** [comment]
The issue is fixed and the new release version is available. Don't forget to leave us a review on https://marketplace.magento.com/tnw-module-stripe.html, we would much appreciate it.
