### ISSUE TITLE
Error in message "We store you payment information"

### ISSUE THREAD

**Issue by jcourtei** [PowerSync/TNW_Stripe#34]
Hello,
Instead of "We store **you** payment information securely on Stripe servers via SSL" it should be "We store **your** payment information securely on Stripe servers via SSL".

**Comment by technweb** [comment]
Pull request created #35

**Comment by technweb** [comment]
The issue is fixed and the new release version is available. Don't forget to leave us a review on https://marketplace.magento.com/tnw-module-stripe.html, we would much appreciate it.
