### ISSUE TITLE
Strong Customer Authentication (SCA) Support

### ISSUE THREAD

**Issue by bobemoe** [PowerSync/TNW_Stripe#46]
Stripe has advised us to contact you to see if any work needs to be done to support the upcoming SCA: Looks like there is plenty of time :)
https://stripe.com/docs/strong-customer-authentication

**Comment by technweb** [comment]
Accepted

**Comment by bobemoe** [comment]
Any news on this? We have until September 14, 2019.

Client wants to know the plan, or if we need to look for alternative modules?

**Comment by technweb** [comment]
@bobemoe its in our backlog and we are targeting to complete this feature in July 2019 (next month). Cheers!

**Comment by bobemoe** [comment]
@technweb thanks, client will be relieved :)

**Comment by clivewalkden** [comment]
Any news on this?

**Comment by moinmalek17** [comment]
Hi,

Is there any update for SCA?

Thanks

**Comment by technweb** [comment]
Development is ongoing and we are aiming to complete this in 2 weeks (including testing). Sorry for the delay guys.

**Comment by moinmalek17** [comment]
Hi there,

is there any update?

Thanks

**Comment by technweb** [comment]
@moinmalek17 yes, we've finished part fo the effort (cards w/o 3D Secure) and are currently working on adding support for cards with 3D Secure. Cheers!

**Comment by moinmalek17** [comment]
@technweb How long it will take with 3D Secure?

Thanks

**Comment by technweb** [comment]
We think we will have a release this week for this feature. Stay tuned.

**Comment by moinmalek17** [comment]
@technweb Thanks

**Comment by technweb** [comment]
We just tagged a new release 2.2.1 which addresses this question.
Feel free to run this command and let us know if you see any isues. 
`composer require tnw/module-stripe=2.2.1`

I will keep this ticket open for a while in case we need to come back.

**Comment by bobemoe** [comment]
@technweb Thanks :) We have installed your update, and tested it with the following card:

> 4000002760003184 - This card requires authentication on all transactions, regardless of how the card is set up. - https://stripe.com/docs/payments/cards/testing#regulatory-cards

The 3D Secure popup appears and if we click to confirm authentication, then the order goes through just fine :) Good work.

However, if we click to fail authentication, then the popup disappears but the AJAX spinner is still present and the page remains greyed out. I can see in the background an error "3D Secure failed" appears on the page (as expected), but it is not possible to edit or resubmit the form or do anything with the greyed out page, apart from refresh.

Looks like the popup was not closed properly?

**Comment by technweb** [comment]
See version `2.2.3` Let me know.

**Comment by moinmalek17** [comment]
Hi,

It's charged twice. One of payment and one of payment intent.

Can you please look into this?

Thanks

**Comment by technweb** [comment]
@moinmalek17 are you using `authorize` or `authorize & capture` setting?
What is the flow where you see this double charge?

**Comment by moinmalek17** [comment]
@technweb It's  authorize and capture method?

It happened every time. In stripe, it showing two payment one of payment and one of payment intent

**Comment by technweb** [comment]
Right, but does it actually charge the CC twice? `Payment` and `payment intent` are two different things.

**Comment by moinmalek17** [comment]
@technweb yes it charged twice

**Comment by moinmalek17** [comment]
for some of the payment not all the payment

**Comment by technweb** [comment]
we cannot seem to reproduce it locally. Can you send us your stripe logs to support at powersync.biz?

**Comment by moinmalek17** [comment]
@technweb Can you please check your email?

Thanks

**Comment by technweb** [comment]
@moinmalek17 thanks for the logs. The new release `2.3.4` addressed the issue (per your email). I am closing this issue. Thanks for helping us with validation!
