### ISSUE TITLE
A source must be attached to a customer to be used as a `payment_method`: error when creating order in Magento admin

### ISSUE THREAD

**Issue by sebdelta** [PowerSync/TNW_Stripe#60]
When you logged in the back-end of Magento and creating an order, you get the error "A source must be attached to a customer to be used as a `payment_method`" after submitting the order. I have put all the required information, a valid SKU with quantities, shipping and new credit card (Stripe Visa test 4242 4242 4242 4242). The error occur because the javascript in the admin is only creating a Stripe source with no Stripe customer information. It is also not creating a Payment Intent. The test was done on a vanilla Magento installation with just the tnw/module-stripe module installed.
It should create a valid payment method with a customer attached to it and a payment intent similar to the front-end process.

Magento EE 2.3.2
tnw/module-stripe 2.2.4

**Comment by technweb** [comment]
@sebdelta thank you for reporting. We fixed this issue in version #78 and its available now.
