### ISSUE TITLE
frontend do not display this payment

### ISSUE THREAD

**Issue by myfyrow** [PowerSync/TNW_Stripe#93]
I configured stripe payment in the background and enabled it. All countries are allowed to use it. However, the payment method of stripe is still not visible on the checkout page, only the other payment I set up before, such as PayPal

**Comment by alexander-babenkocommerce** [comment]
Hi, @myfyrow ​
These versions have no known issues.
Most likely the issue is in customization. To determine it, we need to debug on your code and database.
It would be ideal to have SSH access for us. Is it possible?

**Comment by alexander-babenkocommerce** [comment]
Closed as no response was taken
