### ISSUE TITLE
magento 2.3 stripe module is not working

### ISSUE THREAD

**Issue by zeshanrahman** [PowerSync/TNW_Stripe#95]
https://marketplace.magento.com/tnw-module-stripe.html

module giving me this error

{"0":"Warning: class_implements(): Class TNW\\Marketing\\Ui\\DataProvider\\DataProvider does not exist and could not be loaded

**Comment by alexander-babenkocommerce** [comment]
Closed as outdated

**Comment by Rafiqul-Islam-Rafiq** [comment]
There is a TNW Marketing Extension in github. there is file dependency with this module. https://github.com/PowerSync/TNW_Marketing
